name: Python Package CI/CD

on:
  push:
    branches:
      - main  # This will trigger the workflow on any push to the "main" branch
  pull_request:
    branches:
      - main  # It will also trigger on pull requests to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt  # If you have a requirements file

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --skip-existing
