name: Python Package CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the "main" branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install only if requirements.txt exists

    - name: Build package
      run: |
        rm -rf dist/  # Clean up old builds
        python setup.py sdist bdist_wheel  # Build package

    - name: Upload package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --skip-existing  # Upload package to PyPI
